### ISSUE TITLE
配置文件的保存地址

### ISSUE THREAD

**Issue by haoasdasdf** [zzcabc/Docker_Buildx_Danmuji#2]
你好，很感谢提供docker版程序。

能否请问配置文件保存在哪里？
比如我将用docker-compose启动并配置好的容器，复制到其他服务器时想保存好配置的文件。
但在以下三个文件夹中均没有发现配置文件。

> /danmuji/Danmuji_log | 弹幕姬保存弹幕文件夹(非必须映射)
> /danmuji/guardFile | 弹幕姬上舰私信文件夹(非必须映射)
> /danmuji/log | 弹幕姬日志文件夹(非必须映射)

另外，网页中导出的配置也没有找到在哪里。

**Comment by zzcabc** [comment]
可以看一下源项目的文档 **首次运行会在项目目录下生成 log日志文件夹 DanmujiProfile配置文件**，如果你想映射配置文件，可以使用 `-v $pwd/DanmujiProfile:/danmuji/DanmujiProfile`
如果使用docker-compose的话可以再
volumes:下面映射 `- /danmuji/DanmujiProfile:/danmuji/DanmujiProfile`

关于网页中导出配置，因为程序运行在docker内部，使用导出的配置在docker内部，下午我看看配置文件在哪，在更新

**Comment by zzcabc** [comment]
如果你想获取DanmujiProfile配置文件
- 第一种方案：创建一个文件，启动时将此文件映射到容器内部
  使用`-v $pwd/DanmujiProfile:/danmuji/DanmujiProfile` 程序在运行过程中会自动生成内容
- 第二种方案：在容器正常运行过程中，使用命令将容器内文件或文件夹复制到宿主机中
   使用`docker  cp 容器名称:容器内部文件或文件夹  复制到宿主机的绝对路径 `
   `docker cp danmuji:/danmuji/DanmujiProfile $pwd/DanmujiProfile` 即可复制到当前路径下

获取导出的配置，会在项目路径下创建set文件夹，并生成set.json文件
- 第一种方案：运行docker加入`-v $pwd/set:/danmuji/set` 导出配置即可在set文件夹中获取配置
- 第二种方案：依旧使用命令复制出来
   `docker cp danmuji:/danmuji/set/set.json $pwd/set.json` 即可复制到当前路径下

**Comment by haoasdasdf** [comment]
非常感谢！很详细的解答！

**Comment by zzcabc** [comment]
> 
最新版的已经可以使用浏览器下载设置，你可以更新到最新版
