### ISSUE TITLE
无法登录？

### ISSUE THREAD

**Issue by itsdapi** [zzcabc/Docker_Buildx_Danmuji#3]
二维码刷不出来 而且网页很卡

**Comment by zzcabc** [comment]
可否告知宿主机架构，启用docker的脚本
我这边只有amd64的主机，并且，docker容器启动第一次无法出现二维码，返回，在登录就出现了，在使用过程中并没有出现网页很卡的感觉

**Comment by itsdapi** [comment]
X86架构 ubuntu 20.04.4 LTS Docker version 20.10.14, build a224086349
----
脚本
docker run -d \
    --name danmuji \
    --dns=223.5.5.5 \
    -p 23333:23333 \
    -e JAVA_OPTS="-Xms64m -Xmx128m" \
    -v /home/docker_config/danmuji/Danmuji_log:/danmuji/Danmuji_log \
    -v /home/docker_config/danmuji/guardFile:/danmuji/guardFile \
    -v /home/docker_config/danmuji/log:/danmuji/log \
    zzcabc/danmuji

**Comment by itsdapi** [comment]
而且网页卡是那种网页未响应 然后整个浏览器都会特别卡的那种

**Comment by zzcabc** [comment]
抱歉，没有遇到过，Java的程序内存要求大，你可以使用`docker restart danmui`重启容器，使用`top`观察Java进程的占用资源情况
