### ISSUE TITLE
unraid 无法安装nvalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by xl-jeeter** [zzcabc/Docker_Buildx_Danmuji#4]
/danmuji/Danmuji_log \
能否更改为小写？

**Comment by zzcabc** [comment]
发一下docker命令

**Comment by xl-jeeter** [comment]
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='danmuji' --net='br0' --ip='192.168.50.30' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="danmuji" -l net.unraid.docker.managed=dockerman -v '/mnt/user/appdata/danmuji/danmuji_log/':'danmuji/danmuji_log':'rw' -v '/mnt/user/appdata/danmuji/guardFile/':'/danmuji/guardFile':'rw' -v '/mnt/user/appdata/danmuji/log/':'/danmuji/log':'rw' 'zzcabc/danmuji'
docker: Error response from daemon: invalid volume specification: '/mnt/user/appdata/danmuji/danmuji_log/:danmuji/danmuji_log:rw': invalid mount config for type "bind": invalid mount path: 'danmuji/danmuji_log' mount path must be absolute.
See 'docker run --help'.

**Comment by xl-jeeter** [comment]
我选择放弃映射目录了。。。。

**Comment by zzcabc** [comment]
看报错是仓库名称必须小写，看看拉的是不是zzcabc/danmuji，或者是映射的没有-e -v这种

**Comment by zzcabc** [comment]
```sh
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/
docker run -d 
--name='danmuji' 
--net='br0' --ip='192.168.50.30' 
-e TZ="Asia/Shanghai" 
-e HOST_OS="Unraid" 
-e HOST_HOSTNAME="Tower" 
-e HOST_CONTAINERNAME="danmuji" -l net.unraid.docker.managed=dockerman 
-v '/mnt/user/appdata/danmuji/danmuji_log/':'danmuji/danmuji_log':'rw' 
-v '/mnt/user/appdata/danmuji/guardFile/':'/danmuji/guardFile':'rw' 
-v '/mnt/user/appdata/danmuji/log/':'/danmuji/log':'rw' 'zzcabc/danmuji'
docker: Error response from daemon: invalid volume specification: '/mnt/user/appdata/danmuji/danmuji_log/:danmuji/danmuji_log:rw': invalid mount config for type "bind": invalid mount path: 'danmuji/danmuji_log' mount path must be absolute.
See 'docker run --help'.
```

我在邮件中看到了日志，你的`danmuji/danmuji_log`是相对路径 改为`/danmuji/Danmuji_log` 绝对路径

或者使用 `-v 本机地址 : /danmuji` 直接映射java jar包的地址，会自动创建对应文件夹
